// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig, env } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // Prisma CLI commands (including migrations) need a session/direct connection.
    // DATABASE_URL remains available for the application's pooled runtime client.
    url: env("DIRECT_URL"),
  },
});
